### ISSUE TITLE
Add Google Drive support for go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-gdrive#2]
## Description

[Google Drive] is a file storage and synchronization service developed by Google.
This project will use [Google Drive]'s native SDK e.g: [google.golang.org/api/drive/v3](https://pkg.go.dev/google.golang.org/api/drive/v3)
to implement [go-storage]'s Storager interface,
enabling users to manipulate data in [Google Drive] through a unified interface.

## Roadmap

- [ ] Implement all interface that Storager required
- [ ] Setup integration tests
- [ ] Add docs in [site](https://github.com/beyondstorage/site)
- [ ] Add examples in [example](https://github.com/beyondstorage/go-storage-example)

[Google Drive]: https://www.google.com/drive/
[go-storage]: https://github.com/beyondstorage/go-storage/

**Comment by Xuanwo** [comment]
@junaire is responsible for this issue.

**Comment by junaire** [comment]
Can we close this now? @Xuanwo
