### ISSUE TITLE
Road map of go-service-gdrive

### ISSUE THREAD

**Issue by junaire** [beyondstorage/go-service-gdrive#6]
## Storager

- [x] `formatError`
- [x] `NewStorager`

## Basic Operations

- [x] List
- [x] Create
- [x] Delete
- [x] Metadata
- [x] Read
- [x] Stat
- [x] Write

## Extended operations

- [ ] Copy
- [x] Move
- [ ] Reach
- [ ] Multipart
- [ ] Append
- [ ] Block
- [ ] Page
- [x] Direr

## Others
- [x] Setup integration tests
- [x] Add docs in site
- [x] Add examples in example

**Comment by Xuanwo** [comment]
Nice job!

**Comment by junaire** [comment]
> Nice job!

Thanks very much for your guidance! I appreciate it!❤️❤️❤️
